apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    tunnel: example-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    ingress:
    - hostname: tunnel.example.com
      service: http://web-service:80
    - hostname: hello.example.com
      service: hello_world
    - service: http_status:404
  