apiVersion: cloudflare.laininthewired.github.io/v1beta1
kind: Cloudflare
metadata:
  labels:
    app.kubernetes.io/name: cloudflared-operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudflare-sample
spec:
  # TODO(user): Add fields here
  replicas: 1
  tunnel_name: "test"
  ingress:
  - hostname: te.qpid.jp
    service: http://nginx-service:80

