apiVersion: cloudflare.laininthewired.github.io/v1beta1
kind: Tunnel
metadata:
  labels:
    app.kubernetes.io/name: cloudflared-operator
    app.kubernetes.io/managed-by: kustomize
  name: tunnel-sample
spec:
  tunnel_name: "test2"
  # TODO(user): Add fields here
